#!/usr/bin/env ruby

require "net/http"
require "uri"

def fetch(uri_str, limit = 10)
  return if limit == 0

  url = URI.parse(uri_str)
  http = Net::HTTP.new(url.host, url.port)
  http.use_ssl = true
  req = Net::HTTP::Get.new(url)
  response = http.request(req)
  
  case response
  when Net::HTTPSuccess     then 
    response.body
  when Net::HTTPRedirection then fetch(response['location'], limit - 1)
  else
    response.error!
  end
end

def speak_tweet_for(handle) 
  twitter_url = "https://www.twitter.com/#{handle}"
  contents = fetch twitter_url
  pinned_count = contents.scan(/Pinned Tweet/).size
  tweets = contents.scan(/ProfileTweet-text.*?</m)
  tweet = tweets[pinned_count]
    .match(/>.*</).to_s()
    .gsub(/&quot;/, '"')
    .gsub(/&#39;/, "'")
    .gsub(/[^\w ]+/,"")
    .gsub(/10A/,"?")
  tweet = tweet.empty? ? "aww shucks. I got nothin." : tweet
  system 'say ' + tweet
end


while true 
  speak_tweet_for ARGV[0]
  break if ARGV[1].nil?
  sleep ARGV[1].to_i
end
